version: '3.9'

services:
  frontend:
    build:
      context: ./src/Nitrilon/Nitrilon.Client/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://nitrilon.noahnielsen.dk

  backend:
    build:
      context: ./src/Nitrilon/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Server=srv-captain--mssql-db;Database=NitrilonDB;User Id=sa;Password=NoahsMSSQLDatabase123!;Encrypt=False;TrustServerCertificate=True;
