import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='min-h-screen'
    >
      <body className={`${inter.className} h-screen`}>
        <main>{children}</main>
        <Toaster
          toastOptions={{
            classNames: {
              error: 'bg-red-500 text-white',
              success: 'bg-green-500 text-white',
              info: 'bg-blue-500 text-white',
              warning: 'bg-yellow-500 text-white',
            },
          }}
        />
      </body>
    </html>
  );
}
