name: Deploy .NET Core API to Azure Web App

on:
  push:
    branches:
      - master  # Or your default branch
    paths:
      - 'src/Nitrilon/Nitrilon.Api/**'  # Adjust this path to where your API project lives

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Since .NET runs well on Windows

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify your .NET version here

    - name: Build and publish .NET Core project
      run: |
        cd src/Nitrilon/Nitrilon.Api
        dotnet publish --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Nitrilon API'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './src/Nitrilon/Nitrilon.Api/publish'
